---
# defaults file for websphere-mq
webspheremq:
  user: mqm
  group: mqm
  command_path: /opt/mqm/bin
  required_directories:
      - "/var/mqm"
      - "/var/mqm/errors"
    sysctl_settings:
    - name: kernel.sem
      value: 600 256000 300 2048
    - name: kernel.shmmax
      value: 18446744073692774399
    - name: kernel.shmmni
      value: 4096
    - name: kernel.shmall
      value: 18446744073692774399
    - name: fs.file-max
      value: 3255749
    - name: net.ipv4.tcp_keepalive_time
      value: 300
